n = 13
(
    SELECT_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_REGION,
    GET_CAR_BRAND,
    GET_PRODUCT_TYPE,
    GET_PRODUCT_SIZE,
    SHOW_PRODUCTS,
) = range(0, n)